version: '3.5'
services:
  pg_nostorya:
    image: postgres:14-alpine
    restart: always
    shm_size: 1g
    environment:
      - POSTGRES_USER=nostorya
      - POSTGRES_PASSWORD=nostorya
      - POSTGRES_DB=nostorya_development
    volumes:
      - pg_nostorya:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis_nostorya:
    image: redis:7-alpine
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - nostorya

networks:
  nostorya:
    name: nostorya

volumes:
  pg_nostorya:
