version: '3.5'
services:
  pg_fabelia:
    image: postgres:14-alpine
    restart: always
    shm_size: 1g
    environment:
      - POSTGRES_USER=fabelia
      - POSTGRES_PASSWORD=fabelia
      - POSTGRES_DB=fabelia_development
    volumes:
      - pg_fabelia:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

volumes:
  pg_fabelia:
